// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9UVMc2yWKZfXDQW9zRnci4PwLt2w42xQ',
    appId: '1:484166284664:web:7b2740e6545245143f448d',
    messagingSenderId: '484166284664',
    projectId: 'rebuild-shopee-13972',
    authDomain: 'rebuild-shopee-13972.firebaseapp.com',
    storageBucket: 'rebuild-shopee-13972.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdcuThjA_WMQWSt7mdbmprFCmL69px7Kw',
    appId: '1:484166284664:android:94f1666c311f5b113f448d',
    messagingSenderId: '484166284664',
    projectId: 'rebuild-shopee-13972',
    storageBucket: 'rebuild-shopee-13972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAacfGsaeJKx1ZhVJshrHORmXHwIgSx-0Q',
    appId: '1:484166284664:ios:9b852b62b3b1ac5f3f448d',
    messagingSenderId: '484166284664',
    projectId: 'rebuild-shopee-13972',
    storageBucket: 'rebuild-shopee-13972.firebasestorage.app',
    iosBundleId: 'com.example.shopee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAacfGsaeJKx1ZhVJshrHORmXHwIgSx-0Q',
    appId: '1:484166284664:ios:9b852b62b3b1ac5f3f448d',
    messagingSenderId: '484166284664',
    projectId: 'rebuild-shopee-13972',
    storageBucket: 'rebuild-shopee-13972.firebasestorage.app',
    iosBundleId: 'com.example.shopee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9UVMc2yWKZfXDQW9zRnci4PwLt2w42xQ',
    appId: '1:484166284664:web:bcd41fdacc37e9883f448d',
    messagingSenderId: '484166284664',
    projectId: 'rebuild-shopee-13972',
    authDomain: 'rebuild-shopee-13972.firebaseapp.com',
    storageBucket: 'rebuild-shopee-13972.firebasestorage.app',
  );
}